apiVersion: v1
kind: Secret
metadata:
  name: analytics-secrets
  namespace: analytics
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "..."
  AWS_SECRET_ACCESS_KEY: "..."
  AWS_REGION: "us-east-1"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/257527265067/EvaluationEvent"
  AWS_ENDPOINT_URL: ""
