apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secrets
  namespace: evaluation
type: Opaque
data:
    REDIS_URL: "cmVkaXM6Ly9ob3N0LmRvY2tlci5pbnRlcm5hbDo2Mzc5"
    SERVICE_API_KEY: dG1fa2V5XzliOWExMTRmOWFmNDQzZjE4OTYzZDllZWUyNTU4N2VlZGFkMjRhM2YzN2ZhMjUyNTI2ZDQ5NmY5YjljZTllMjY=