apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-config
  namespace: evaluation
data:
  PORT: "8004"
  REDIS_URL: "redis://redis:6379"
  FLAG_SERVICE_URL: "http://flag-service:8002"
  TARGETING_SERVICE_URL: "http://targeting-service:8003"
  SERVICE_API_KEY: "tm_key_local_service_123"
  AWS_REGION: "us-east-1"
  AWS_SQS_URL: ""
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"