apiVersion: v1
kind: ConfigMap
metadata:
  name: targeting-config
  namespace: targeting
data:
  PORT: "8003"
  DATABASE_URL: "postgres://postgres:postgres@postgres-flags:5432/flags_db?sslmode=disable"
  AUTH_SERVICE_URL: "http://auth-service:8001"