apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-deployment
  namespace: evaluation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation
  template:
    metadata:
      labels:
        app: evaluation
    spec:
      containers:
      - name: evaluation
        image: evaluation:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8004
        envFrom:
          - secretRef:
              name: evaluation-secrets
          - configMapRef:
              name: evaluation-config