apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation
  namespace: evaluation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation
  template:
    metadata:
      labels:
        app: evaluation
    spec:
      containers:
      - name: evaluation
        image: 257527265067.dkr.ecr.us-east-1.amazonaws.com/fiap-fase2/evaluation-service:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8004
        envFrom:
          - secretRef:
              name: evaluation-secrets
          - configMapRef:
              name: evaluation-config
