apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag
  namespace: flag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flag
  template:
    metadata:
      labels:
        app: flag
    spec:
      containers:
      - name: flag
        image: 257527265067.dkr.ecr.us-east-1.amazonaws.com/fiap-fase2/flag-service:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002
        envFrom:
        - secretRef:
            name: flag-secrets
        - configMapRef:
            name: flag-config
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
